name: Test, Coverage, Build and Release apks
on: push
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
          
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: clean cache
        run: flutter clean
        
      - name: GET Flutter
        run: flutter pub get
        
      #- name: Lint code Flutter
      #  run: flutter analyze
      
      - name: FLutter Lint
        uses: zgosalvez/github-actions-analyze-dart@v1
      
      - name : upgrade flutter
        run: flutter upgrade
        
      - name : flutter pub 
        run: flutter pub upgrade
        
      - name: flutter test coverage
        run: flutter test --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info

      - run: flutter build apk --debug --split-per-abi --no-sound-null-safety

      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*.apk"
          token: ${{ secrets.TOKEN }}
          tag: v2.0
